/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as deFiSol from "./DeFI.sol";
export type { deFiSol };
export type { DAO } from "./DAO";
export type { Game } from "./Game";
export type { GameNFT } from "./GameNFT";
export type { GameShop } from "./GameShop";
export type { GameToken } from "./GameToken";
export type { Leaderboard } from "./Leaderboard";
export type { Shop } from "./Shop";
export type { User } from "./User";
