/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Leaderboard {
  export type LeaderboardInternalStruct = {
    winners: AddressLike[];
    data: BigNumberish[];
  };

  export type LeaderboardInternalStructOutput = [
    winners: string[],
    data: bigint[]
  ] & { winners: string[]; data: bigint[] };
}

export interface LeaderboardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "initializeLeaderboard"
      | "updateLeaderboard"
      | "viewLeaderboard"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "initializeLeaderboard",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLeaderboard",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "viewLeaderboard",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "initializeLeaderboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLeaderboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewLeaderboard",
    data: BytesLike
  ): Result;
}

export interface Leaderboard extends BaseContract {
  connect(runner?: ContractRunner | null): Leaderboard;
  waitForDeployment(): Promise<this>;

  interface: LeaderboardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  initializeLeaderboard: TypedContractMethod<
    [game: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateLeaderboard: TypedContractMethod<
    [game: BigNumberish, to: AddressLike, data: BigNumberish],
    [void],
    "nonpayable"
  >;

  viewLeaderboard: TypedContractMethod<
    [game: BigNumberish],
    [Leaderboard.LeaderboardInternalStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "initializeLeaderboard"
  ): TypedContractMethod<[game: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateLeaderboard"
  ): TypedContractMethod<
    [game: BigNumberish, to: AddressLike, data: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "viewLeaderboard"
  ): TypedContractMethod<
    [game: BigNumberish],
    [Leaderboard.LeaderboardInternalStructOutput],
    "view"
  >;

  filters: {};
}
