/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface UserInterface extends Interface {
  getFunction(
    nameOrSignature: "getUserData" | "initializeUserData" | "updateUserData"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getUserData",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeUserData",
    values: [BigNumberish, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updateUserData",
    values: [BigNumberish, AddressLike, string[], BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getUserData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeUserData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateUserData",
    data: BytesLike
  ): Result;
}

export interface User extends BaseContract {
  connect(runner?: ContractRunner | null): User;
  waitForDeployment(): Promise<this>;

  interface: UserInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getUserData: TypedContractMethod<
    [game: BigNumberish, user: AddressLike],
    [[string[], bigint[]] & { userKeys: string[]; values: bigint[] }],
    "view"
  >;

  initializeUserData: TypedContractMethod<
    [game: BigNumberish, userKeys: string[]],
    [void],
    "nonpayable"
  >;

  updateUserData: TypedContractMethod<
    [
      game: BigNumberish,
      user: AddressLike,
      userKeys: string[],
      values: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getUserData"
  ): TypedContractMethod<
    [game: BigNumberish, user: AddressLike],
    [[string[], bigint[]] & { userKeys: string[]; values: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "initializeUserData"
  ): TypedContractMethod<
    [game: BigNumberish, userKeys: string[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateUserData"
  ): TypedContractMethod<
    [
      game: BigNumberish,
      user: AddressLike,
      userKeys: string[],
      values: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
